[[plugins]]
repo = 'lambdalisue/fern.vim'
on_cmd = 'Fern'
hook_add = '''
nnoremap <silent> <Space>f :Fern -drawer -toggle .<CR>
'''

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = 'go'
hook_add = '''
augroup MyGoAutoCmd
  autocmd!
  autocmd BufNewFile,BufRead *.go setlocal noexpandtab tabstop=4 shiftwidth=4
augroup END
if !executable('goimports')
  execute '!go get golang.org/x/tools/cmd/goimports'
endif
'''

[[plugins]]
repo = 'mattn/vim-goaddtags'
on_ft = 'go'
hook_add = '''
if !executable('gomodifytags')
  execute '!go get github.com/fatih/gomodifytags'
endif
'''

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'
hook_add = '''
let g:vinarise_enable_auto_detect = 1
let g:vinarise_guifont = 'Courier\ 10\ Pitch:h14'
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
on_if = '!has("nvim")'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
on_if = '!has("nvim")'
depends = ['vim-lsp', 'asyncomplete.vim']

[[plugins]]
repo = 'prabirshrestha/asyncomplete-buffer.vim'
on_if = '!has("nvim")'
depends = ['asyncomplete.vim']
hook_source = '''
augroup asyncomplete_buffer_setup
  au!
  call asyncomplete#register_source(asyncomplete#sources#buffer#get_source_options({
    \ 'name': 'buffer',
    \ 'whitelist': ['*'],
    \ 'completor': function('asyncomplete#sources#buffer#completor'),
    \ 'config': {
    \    'max_buffer_size': 5000000,
    \  },
    \ }))
augroup END
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-file.vim'
on_if = '!has("nvim")'
depends = ['asyncomplete.vim']
hook_source = '''
augroup asyncomplete_file_setup
  au!
  call asyncomplete#register_source(asyncomplete#sources#file#get_source_options({
    \ 'name': 'file',
    \ 'whitelist': ['*'],
    \ 'priority': 10,
    \ 'completor': function('asyncomplete#sources#file#completor'),
    \ }))
augroup END
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'
hook_add = '''
let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
