[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim']
hook_add = '''
source ~/.config/vim/vim-lsp.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['vim-lsp']

[[plugins]]
repo = 'tsuyoshicho/vim-efm-langserver-settings'
depends = ['vim-lsp']
