[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'lifepillar/vim-solarized8'
hook_add = '''
  set background=dark
  colorscheme solarized8_high
'''
