[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = '''
  source ~/.config/nvim/deoplete.vim
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
  source ~/.config/nvim/denite.vim
'''
hook_source = '''
  source ~/.config/nvim/denite_source.vim
'''

[[plugins]]
repo = 'raghur/fruzzy'
on_source = ['denite.nvim']
hook_source = 'let g:fruzzy#sortonempty = 0'
hook_post_update = 'call fruzzy#install()'

[[plugins]]
repo = 'Shougo/defx.nvim'
depends = ['vim-choosewin']
hook_add = '''
  source ~/.config/nvim/defx.vim
'''
hook_post_source = '''
  call defx#custom#option('_', {
      \ 'show_ignored_files': 1,
      \ })
'''

[[plugins]]
repo = 'chrisbra/vim-zsh'
on_ft = 'zsh'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'dense-analysis/ale'
on_ft = ['python', 'sh', 'terraform', 'json', 'yaml', 'Dockerfile', 'make', 'javascript', 'typescript', 'typescriptreact', 'bash', 'zsh']
hook_add = '''
  source ~/.config/nvim/ale.vim
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = 'terraform'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
  let g:vim_json_syntax_conceal = 1
'''

[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = 'markdown'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
  let g:vim_markdown_folding_disabled = 1
'''

[[plugins]]
repo = 'previm/previm'
on_ft = 'markdown'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = 'markdown'

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript', 'typescript', 'typescriptreact']

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = ['typescript', 'typescriptreact']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript', 'typescriptreact']
depends = ['vim-javascript', 'yats.vim']
hook_add = '''
  let g:vim_jsx_pretty_colorful_config = 1
  let g:vim_jsx_pretty_enable_jsx_highlight = 1
'''

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
depends = 'vim-lsp'
hook_add = '''
  source ~/.config/vim/go.vim
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
depends = ['deoplete.nvim']

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
depends = ['async.vim', 'deoplete-vim-lsp']
on_ft = ['go', 'typescript', 'Dockerfile', 'sh', 'typescriptreact', 'sql', 'python', 'bash']
hook_add = '''
  source ~/.config/vim/lsp.vim
'''
hook_post_source = '''
  augroup LspEnable
    autocmd!
    autocmd BufWinEnter *.go  :call lsp#enable()
    autocmd BufWinEnter *.py  :call lsp#enable()
    autocmd BufWinEnter *.ts  :call lsp#enable()
    autocmd BufWinEnter *.tsx :call lsp#enable()
    autocmd BufWinEnter *.js  :call lsp#enable()
  augroup END
'''

[[plugins]]
repo = 'ryanolsonx/vim-lsp-typescript'
on_ft = ['typescript']
depends = ['vim-lsp']

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'javascript.jsx', 'typescript.tsx', 'typescriptreact']
hook_add = '''
  let g:user_emmet_settings = {
  \  'javascript': {
  \      'extends': 'jsx',
  \  },
  \  'typescript': {
  \      'extends': 'jsx',
  \  },
  \}
'''

[[plugins]]
repo = 'chr4/nginx.vim'
on_ft = ['nginx']

[[plugins]]
repo = 't9md/vim-choosewin'

[[plugins]]
repo = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_ft = ['vim']

[[plugins]]
repo = 'SirVer/ultisnips'
depends = ['honza/vim-snippets']
on_ft = ["go", "yaml", "sh", 'Dockerfile', 'yaml.docker-compose', 'python']
hook_add = '''
  let g:UltiSnipsExpandTrigger="<tab>"
'''

[[plugins]]
repo = 'honza/vim-snippets'
on_ft = ["go", "yaml", "sh", 'Dockerfile', 'yaml.docker-compose', 'python']

[[plugins]]
repo = 'andrewstuart/vim-kubernetes'
on_ft = ["yaml"]

[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['Dockerfile', 'yaml.docker-compose']
