[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'sainnhe/gruvbox-material'

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  source ~/.config/vim/submode.vim
'''
