[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tomasr/molokai'
hook_add = '''
augroup setcolorscheme
    autocmd VimEnter * nested colorscheme molokai
augroup END
'''

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
