[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  colorscheme iceberg
'''

[[plugins]]
repo = 'kana/vim-submode'
hook_add = '''
  call submode#enter_with('winsize', 'n', '', '<C-w><C-l>', '<C-w>>')
  call submode#enter_with('winsize', 'n', '', '<C-w><C-h>', '<C-w><')
  call submode#enter_with('winsize', 'n', '', '<C-w><C-k>', '<C-w>+')
  call submode#enter_with('winsize', 'n', '', '<C-w><C-j>', '<C-w>-')
  call submode#map('winsize', 'n', '', '<C-l>', '<C-w>>')
  call submode#map('winsize', 'n', '', '<C-h>', '<C-w><')
  call submode#map('winsize', 'n', '', '<C-k>', '<C-w>+')
  call submode#map('winsize', 'n', '', '<C-j>', '<C-w>-')
'''
